//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.CodeDom;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Flai;
using Flai.Diagnostics;
using Flai.Graphics;
using Flai.Networking;
using Flai.Scene;
using UnityEngine;

using UnityObject = UnityEngine.Object;

#region Game Object & Component Extensions

public static class GameObjectExtensions
{
    #region Get/Has/Remove etc

    public static bool TryGet<T>(this GameObject gameObject, out T value)
        where T : Component
    {
        value = gameObject.GetComponent<T>();
        return value != null;
    }

    public static bool TryGet<T>(this Component component, out T value)
        where T : Component
    {
        value = component.GetComponent<T>();
        return value != null;
    }

    public static T TryGet<T>(this GameObject gameObject)
        where T : Component
    {
        return gameObject.GetComponent<T>();
    }

    public static T TryGet<T>(this Component component)
        where T : Component
    {
        return component.GetComponent<T>();
    }

    public static T GetOrAdd<T>(this GameObject gameObject)
        where T : Component
    {
        T value;
        if (gameObject.TryGet<T>(out value))
        {
            return value;
        }

        return gameObject.Add<T>();
    }

    public static T Get<T>(this GameObject gameObject)
        where T : Component
    {
        return gameObject.GetComponent<T>();
    }

    public static T GetInterface<T>(this GameObject gameObject)
        where T : class
    {
        return gameObject.GetComponent(typeof(T)) as T;
    }

    public static T GetInChildren<T>(this GameObject gameObject)
       where T : Component
    {
        return gameObject.GetComponentInChildren<T>();
    }

    public static T GetInParent<T>(this GameObject gameObject)
      where T : Component
    {
        return gameObject.GetComponentInParent<T>();
    }

    public static bool Has<T>(this GameObject gameObject)
        where T : Component
    {
        return gameObject.GetComponent<T>() != null;
    }

    public static bool HasInChildren<T>(this GameObject gameObject)
        where T : Component
    {
        return gameObject.GetComponentInChildren<T>() != null;
    }

    public static bool HasInParent<T>(this GameObject gameObject)
       where T : Component
    {
        return gameObject.GetComponentInParent<T>() != null;
    }

    public static T Add<T>(this GameObject gameObject)
        where T : Component
    {
        return gameObject.AddComponent<T>();
    }

    public static bool Remove<T>(this GameObject gameObject)
        where T : Component
    {
        if (!gameObject.Has<T>())
        {
            return false;
        }


        T value = gameObject.Get<T>();
        GameObject.Destroy(value);
        return true;
    }

    public static T GetOrAdd<T>(this Component component)
        where T : Component
    {
        T value;
        if (component.TryGet<T>(out value))
        {
            return value;
        }

        return component.Add<T>();
    }

    public static T Get<T>(this Component component)
        where T : Component
    {
        return component.GetComponent<T>();
    }

    public static T GetInterface<T>(this Component component)
      where T : class
    {
        return component.GetComponent(typeof(T)) as T;
    }

    public static T GetInChildren<T>(this Component component)
      where T : Component
    {
        return component.GetComponentInChildren<T>();
    }

    public static T GetInParent<T>(this Component component)
      where T : Component
    {
        return component.GetComponentInParent<T>();
    }

    public static bool Has<T>(this Component component)
        where T : Component
    {
        return component.GetComponent<T>() != null;
    }

    public static bool HasInChildren<T>(this Component component)
        where T : Component
    {
        return component.GetComponentInChildren<T>() != null;
    }

    public static bool HasInParent<T>(this Component component)
       where T : Component
    {
        return component.GetComponentInParent<T>() != null;
    }

    public static T Add<T>(this Component component)
        where T : Component
    {
        return component.gameObject.AddComponent<T>();
    }

    public static bool Remove<T>(this Component component)
        where T : Component
    {
        if (!component.Has<T>())
        {
            return false;
        }

        T value = component.Get<T>();
        Component.Destroy(value);
        return true;
    }

    public static T GetComponentInChildren<T>(this GameObject gameObject, bool searchRecursively)
        where T : Component
    {
        return Scene.GetComponentInChildren<T>(gameObject.transform, searchRecursively);
    }

    public static T GetComponentInChildren<T>(this Component component, bool searchRecursively)
        where T : Component
    {
        return Scene.GetComponentInChildren<T>(component.transform, searchRecursively);
    }

    public static T GetComponentInChildren<T>(this Transform transform, bool searchRecursively)
        where T : Component
    {
        return Scene.GetComponentInChildren<T>(transform, searchRecursively);
    }


    public static void GetComponentsInChildren<T>(this GameObject gameObject, ICollection<T> collection, bool searchRecursively = true)
        where T : Component
    {
        Scene.GetComponentsInChildren<T>(gameObject.transform, collection, searchRecursively);
    }

    public static void GetComponentsInChildren<T>(this Component component, ICollection<T> collection, bool searchRecursively = true)
        where T : Component
    {
        Scene.GetComponentsInChildren<T>(component.transform, collection, searchRecursively);
    }

    public static void GetComponentsInChildren<T>(this Transform transform, ICollection<T> collection, bool searchRecursively = true)
        where T : Component
    {
        Scene.GetComponentsInChildren<T>(transform, collection, searchRecursively);
    }

    #endregion

    #region Destroy

    public static void DontDestroyOnLoad(this UnityObject obj)
    {
        UnityObject.DontDestroyOnLoad(obj);
    }

    public static void Destroy(this GameObject gameObject)
    {
        GameObject.Destroy(gameObject);
    }

    public static void DestroyIfNotNull(this GameObject gameObject)
    {
        if (gameObject != null)
        {
            GameObject.Destroy(gameObject);
        }
    }

    public static void DestroyImmediateIfNotNull(this GameObject gameObject)
    {
        if (gameObject != null)
        {
            GameObject.DestroyImmediate(gameObject);
        }
    }

    public static void DestroyGameObject(this Component component)
    {
        GameObject.Destroy(component.gameObject);
    }

    public static void DestroyImmediateGameObject(this Component component)
    {
        GameObject.DestroyImmediate(component.gameObject);
    }

    public static void Destroy(this Component component)
    {
        Component.Destroy(component);
    }

    public static void DestroyImmediate(this Component component)
    {
        Component.DestroyImmediate(component);
    }

    public static bool IsDestroyed(this UnityObject obj)
    {
        // unity overloads the == operator on UnityEngine.Object and returns null if it is destroyed
        return obj == null;
    }

    public static void DestroyAllChildren(this GameObject gameObject)
    {
        foreach (var child in gameObject.GetChildren().ToArray()) // toarray necessary?
        {
            child.DestroyIfNotNull();
        }
    }

    public static void DestroyAllChildrenImmediate(this GameObject gameObject)
    {
        foreach (var child in gameObject.GetChildren().ToArray()) // toarray necessary?
        {
            child.DestroyImmediateIfNotNull();
        }
    }

    #endregion

    #region Child / Parent stuff

    #region GetChild/GetChildren

    #region GetChild/GetChildRecursively

    public static GameObject GetChild(this FlaiScript flaiScript, string name)
    {
        return flaiScript.Transform.GetChild(name);
    }

    public static GameObject GetChild(this Component component, string name)
    {
        return component.transform.GetChild(name);
    }

    public static GameObject GetChild(this GameObject gameObject, string name)
    {
        return gameObject.transform.GetChild(name);
    }

    public static GameObject GetChild(this Transform transform, string name)
    {
        Transform child = transform.FindChild(name);
        if (child == null)
        {
            return null;
        }

        return child.gameObject;
    }

    public static GameObject GetChildRecursively(this Component component, string name)
    {
        return component.transform.GetChildRecursively(name);
    }

    public static GameObject GetChildRecursively(this GameObject gameObject, string name)
    {
        return gameObject.transform.GetChildRecursively(name);
    }

    public static GameObject GetChildRecursively(this Transform transform, string name)
    {
        for (int i = 0; i < transform.childCount; i++)
        {
            var child = transform.GetChild(i);
            if (child.name == name)
            {
                return child.gameObject;
            }

            var result = child.GetChildRecursively(name);
            if (result != null)
            {
                return result;
            }
        }

        return null;
    }

    #endregion

    #region GetChildrenTransforms / GetChildrensTransformsRecursively

    // faster
    public static IEnumerable<Transform> GetChildrenTransforms(this GameObject gameObject)
    {
        return gameObject.transform.GetChildrenTransforms();
    }

    public static IEnumerable<Transform> GetChildrenTransforms(this Component component)
    {
        return component.transform.GetChildrenTransforms();
    }

    public static IEnumerable<Transform> GetChildrenTransforms(this FlaiScript flaiScript)
    {
        return flaiScript.Transform.GetChildrenTransforms();
    }

    public static IEnumerable<Transform> GetChildrenTransforms(this Transform transform)
    {
        for (int i = 0; i < transform.childCount; i++)
        {
            yield return transform.GetChild(i);
        }
    }

    public static IEnumerable<Transform> GetChildrenTransformsRecursively(this GameObject gameObject)
    {
        return gameObject.transform.GetChildrenTransformsRecursively();
    }

    public static IEnumerable<Transform> GetChildrenTransformsRecursively(this Component component)
    {
        return component.transform.GetChildrenTransformsRecursively();
    }

    public static IEnumerable<Transform> GetChildrenTransformsRecursively(this Transform transform)
    {
        for (int i = 0; i < transform.childCount; i++)
        {
            Transform child = transform.GetChild(i);
            yield return child;
            foreach (var other in child.GetChildrenTransformsRecursively())
            {
                yield return other;
            }
        }
    }

    #endregion

    #region GetChildren/GetChildrenRecursively

    public static IEnumerable<GameObject> GetChildren(this GameObject gameObject)
    {
        return gameObject.transform.GetChildren();
    }

    public static IEnumerable<GameObject> GetChildren(this Component component)
    {
        return component.transform.GetChildren();
    }

    public static IEnumerable<GameObject> GetChildren(this FlaiScript flaiScript)
    {
        return flaiScript.Transform.GetChildren();
    }

    public static IEnumerable<GameObject> GetChildren(this Transform transform)
    {
        for (int i = 0; i < transform.childCount; i++)
        {
            yield return transform.GetChild(i).gameObject;
        }
    }

    public static IEnumerable<GameObject> GetChildrenRecursively(this GameObject gameObject)
    {
        return gameObject.transform.GetChildrenRecursively();
    }

    public static IEnumerable<GameObject> GetChildrenRecursively(this Component component)
    {
        return component.transform.GetChildrenRecursively();
    }

    public static IEnumerable<GameObject> GetChildrenRecursively(this Transform transform)
    {
        for (int i = 0; i < transform.childCount; i++)
        {
            Transform child = transform.GetChild(i);
            yield return child.gameObject;
            foreach (GameObject other in child.GetChildrenRecursively())
            {
                yield return other;
            }
        }
    }

    #endregion

    #endregion

    #region Other

    public static GameObject GetParent(this GameObject gameObject)
    {
        var parentTransform = gameObject.transform.parent;
        if (parentTransform != null)
        {
            return parentTransform.gameObject;
        }

        return null;
    }

    public static GameObject GetParent(this Transform transform)
    {
        var parentTransform = transform.parent;
        if (parentTransform != null)
        {
            return parentTransform.gameObject;
        }

        return null;
    }

    public static void SetParent(this GameObject gameObject, GameObject parent)
    {
        gameObject.transform.parent = (parent == null) ? null : parent.transform;
    }

    public static void SetParent(this GameObject gameObject, GameObject parent, bool worldPositionStays)
    {
        gameObject.transform.SetParent((parent != null) ? parent.transform : null, worldPositionStays);
    }

    public static void SetParent(this Transform transform, Transform parent)
    {
        transform.parent = parent;
    }

    public static void AttachChild(this GameObject gameObject, GameObject child)
    {
        child.transform.parent = gameObject.transform;
    }

    public static void AttachChild(this Transform transform, Transform child)
    {
        child.parent = transform;
    }

    #endregion

    #endregion

    #region Get Position/Scale/Rotation 2D

    public static Vector2f GetPosition2D(this Transform transform)
    {
        return (Vector2f)transform.position;
    }

    public static Vector3 GetPosition(this GameObject gameObject)
    {
        return gameObject.transform.position;
    }

    public static Vector2f GetLocalPosition2D(this Transform transform)
    {
        return (Vector2f)transform.localPosition;
    }

    public static Vector2f GetPosition2D(this GameObject gameObject)
    {
        return gameObject.transform.GetPosition2D();
    }

    public static Vector2f GetLocalPosition2D(this GameObject gameObject)
    {
        return gameObject.transform.GetLocalPosition2D();
    }

    public static Vector2f GetPosition2D(this Component component)
    {
        return component.transform.GetPosition2D();
    }

    public static Vector2f GetLocalPosition2D(this Component component)
    {
        return component.transform.GetLocalPosition2D();
    }

    public static Vector2f GetScale2D(this Transform transform)
    {
        return new Vector2f(transform.localScale.x, transform.localScale.y);
    }

    public static Vector2f GetScale2D(this GameObject gameObject)
    {
        return gameObject.transform.GetScale2D();
    }

    public static Vector2f GetScale2D(this Component component)
    {
        return component.transform.GetScale2D();
    }

    public static float GetRotation2D(this Transform transform)
    {
        return transform.eulerAngles.z;
    }

    public static float GetLocalRotation2D(this Transform transform)
    {
        return transform.localEulerAngles.z;
    }

    public static float GetRotation2D(this GameObject gameObject)
    {
        return gameObject.transform.GetRotation2D();
    }

    public static float GetLocalRotation2D(this GameObject gameObject)
    {
        return gameObject.transform.GetLocalRotation2D();
    }

    public static float GetRotation2D(this Component component)
    {
        return component.transform.eulerAngles.z;
    }

    public static float GetLocalRotation2D(this Component component)
    {
        return component.transform.localEulerAngles.z;
    }

    #endregion

    #region Set Position/Scale/Rotation 2D

    public static void SetPosition2D(this Transform transform, float x, float y)
    {
        transform.position = new Vector3(x, y, transform.position.z);
    }

    public static void SetPosition2D(this Transform transform, Vector2 position)
    {
        transform.position = new Vector3(position.x, position.y, transform.position.z);
    }

    public static void SetPosition2D(this Component component, float x, float y)
    {
        component.transform.position = new Vector3(x, y, component.transform.position.z);
    }

    public static void SetPosition2D(this Component component, Vector2 position)
    {
        component.transform.position = new Vector3(position.x, position.y, component.transform.position.z);
    }

    public static void SetPosition2D(this GameObject gameObject, float x, float y)
    {
        gameObject.transform.SetPosition2D(x, y);
    }

    public static void SetPosition2D(this GameObject gameObject, Vector2 position)
    {
        gameObject.transform.SetPosition2D(position);
    }

    public static void SetPosition(this GameObject gameObject, float x, float y, float z)
    {
        gameObject.transform.position = new Vector3(x, y, z);
    }

    public static void SetPosition(this GameObject gameObject, Vector3 position)
    {
        gameObject.transform.position = position;
    }

    public static void SetPosition(this GameObject gameObject, Vector2 position, float z)
    {
        gameObject.transform.position = new Vector3(position.x, position.y, z);
    }

    public static void SetScale2D(this Transform transform, float scale)
    {
        transform.localScale = new Vector3(scale, scale, transform.localScale.z);
    }

    public static void SetScale2D(this Transform transform, float x, float y)
    {
        transform.localScale = new Vector3(x, y, transform.localScale.z);
    }

    public static void SetScale2D(this Transform transform, Vector2 scale)
    {
        transform.localScale = new Vector3(scale.x, scale.y, transform.localScale.z);
    }

    public static void SetScale2D(this GameObject gameObject, float scale)
    {
        gameObject.transform.SetScale2D(scale);
    }

    public static void SetScale2D(this GameObject gameObject, float x, float y)
    {
        gameObject.transform.SetScale2D(x, y);
    }

    public static void SetScale2D(this GameObject gameObject, Vector2 scale)
    {
        gameObject.transform.SetScale2D(scale);
    }

    public static void SetRotation2D(this Transform transform, float rotation)
    {
        transform.eulerAngles = new Vector3(0, 0, rotation);
    }

    public static void SetRotation2D(this GameObject gameObject, float rotation)
    {
        gameObject.transform.eulerAngles = new Vector3(0, 0, rotation);
    }

    #region Local

    public static void SetLocalPosition2D(this Transform transform, float x, float y)
    {
        transform.localPosition = new Vector3(x, y, transform.position.z);
    }

    public static void SetLocalPosition2D(this Transform transform, Vector2 position)
    {
        transform.localPosition = new Vector3(position.x, position.y, transform.position.z);
    }

    public static void SetLocalPosition2D(this GameObject gameObject, float x, float y)
    {
        gameObject.transform.SetLocalPosition2D(x, y);
    }

    public static void SetLocalPosition2D(this GameObject gameObject, Vector2 position)
    {
        gameObject.transform.SetLocalPosition2D(position);
    }

    public static void SetLocalPosition(this GameObject gameObject, float x, float y, float z)
    {
        gameObject.transform.localPosition = new Vector3(x, y, z);
    }

    public static void SetLocalPosition(this GameObject gameObject, Vector3 position)
    {
        gameObject.transform.localPosition = position;
    }

    public static void SetLocalPosition(this GameObject gameObject, Vector2 position, float z)
    {
        gameObject.transform.localPosition = new Vector3(position.x, position.y, z);
    }

    public static void SetLocalRotation2D(this Transform transform, float rotation)
    {
        transform.localEulerAngles = new Vector3(0, 0, rotation);
    }

    public static void SetLocalRotation2D(this GameObject gameObject, float rotation)
    {
        gameObject.transform.localEulerAngles = new Vector3(0, 0, rotation);
    }

    #endregion

    #endregion

    #region Add XXX

    public static Vector2f AddPosition2D(this Transform transform, Vector2f amount)
    {
        transform.position += amount.ToVector3();
        return transform.position;
    }

    public static Vector2f AddPosition2D(this GameObject gameObject, Vector2f amount)
    {
        return gameObject.transform.AddPosition2D(amount);
    }

    #endregion

    #region Set Scale X Y Z

    public static void SetScaleX(this Transform transform, float value)
    {
        transform.localScale = new Vector3(value, transform.localScale.y, transform.localScale.z);
    }

    public static void SetScaleY(this Transform transform, float value)
    {
        transform.localScale = new Vector3(transform.localScale.x, value, transform.localScale.z);
    }

    public static void SetScaleZ(this Transform transform, float value)
    {
        transform.localScale = new Vector3(transform.localScale.x, transform.localScale.y, value);
    }

    #endregion

    #region Set Position X Y Z

    public static void SetPositionX(this Transform transform, float value)
    {
        transform.position = new Vector3(value, transform.position.y, transform.position.z);
    }

    public static void SetPositionY(this Transform transform, float value)
    {
        transform.position = new Vector3(transform.position.x, value, transform.position.z);
    }

    public static void SetPositionZ(this Transform transform, float value)
    {
        transform.position = new Vector3(transform.position.x, transform.position.y, value);
    }

    public static void SetLocalPositionX(this Transform transform, float value)
    {
        transform.localPosition = new Vector3(value, transform.localPosition.y, transform.localPosition.z);
    }

    public static void SetLocalPositionY(this Transform transform, float value)
    {
        transform.localPosition = new Vector3(transform.localPosition.x, value, transform.localPosition.z);
    }

    public static void SetLocalPositionZ(this Transform transform, float value)
    {
        transform.localPosition = new Vector3(transform.localPosition.x, transform.localPosition.y, value);
    }

    public static void SetRotationX(this Transform transform, float value)
    {
        transform.eulerAngles = new Vector3(value, transform.eulerAngles.y, transform.eulerAngles.z);
    }

    public static void SetRotationY(this Transform transform, float value)
    {
        transform.eulerAngles = new Vector3(transform.eulerAngles.x, value, transform.eulerAngles.z);
    }

    public static void SetRotationZ(this Transform transform, float value)
    {
        transform.eulerAngles = new Vector3(transform.eulerAngles.x, transform.eulerAngles.y, value);
    }

    public static void SetLocalRotationX(this Transform transform, float value)
    {
        transform.localEulerAngles = new Vector3(value, transform.localEulerAngles.y, transform.localEulerAngles.z);
    }

    public static void SetLocalRotationY(this Transform transform, float value)
    {
        transform.localEulerAngles = new Vector3(transform.localEulerAngles.x, value, transform.localEulerAngles.z);
    }

    public static void SetLocalRotationZ(this Transform transform, float value)
    {
        transform.localEulerAngles = new Vector3(transform.localEulerAngles.x, transform.localEulerAngles.y, value);
    }

    #endregion

    #region Instantiate

    public static GameObject Instantiate(this GameObject gameObject)
    {
        return (GameObject)GameObject.Instantiate(gameObject);
    }

    public static GameObject Instantiate(this GameObject gameObject, Vector3 position)
    {
        return (GameObject)GameObject.Instantiate(gameObject, position, Quaternion.identity);
    }

    public static GameObject Instantiate(this GameObject gameObject, Vector3 position, Quaternion rotation)
    {
        return (GameObject)GameObject.Instantiate(gameObject, position, rotation);
    }

    public static GameObject Instantiate(this GameObject gameObject, Vector2f position, float rotation2D)
    {
        return (GameObject)GameObject.Instantiate(gameObject, position, Quaternion.Euler(0, 0, rotation2D));
    }

    public static T Instantiate<T>(this T obj)
        where T : UnityObject
    {
        return (T)UnityObject.Instantiate(obj);
    }

    public static GameObject InstantiateIfNotNull(this GameObject gameObject)
    {
        if (gameObject == null)
        {
            return null;
        }

        return (GameObject)GameObject.Instantiate(gameObject);
    }

    public static GameObject InstantiateIfNotNull(this GameObject gameObject, Vector3 position)
    {
        if (gameObject == null)
        {
            return null;
        }

        return (GameObject)GameObject.Instantiate(gameObject, position, Quaternion.identity);
    }

    public static GameObject InstantiateIfNotNull(this GameObject gameObject, Vector3 position, Quaternion rotation)
    {
        if (gameObject == null)
        {
            return null;
        }

        return (GameObject)GameObject.Instantiate(gameObject, position, rotation);
    }

    public static GameObject InstantiateIfNotNull(this GameObject gameObject, Vector2f position, float rotation2D)
    {
        if (gameObject == null)
        {
            return null;
        }

        return (GameObject)GameObject.Instantiate(gameObject, position, Quaternion.Euler(0, 0, rotation2D));
    }

    public static T InstantiateIfNotNull<T>(this T obj)
        where T : UnityObject
    {
        if (obj == null)
        {
            return null;
        }

        return (T)UnityObject.Instantiate(obj);
    }

    #region Network Instantiate

    public static GameObject NetworkInstantiate(this GameObject gameObject)
    {
        return gameObject.NetworkInstantiate(Vector2f.Zero, 0, 0);
    }

    public static GameObject NetworkInstantiate(this GameObject gameObject, Vector2f position)
    {
        return gameObject.NetworkInstantiate(position, 0, 0);
    }

    public static GameObject NetworkInstantiate(this GameObject gameObject, Vector2f position, float rotation)
    {
        return gameObject.NetworkInstantiate(position, rotation, 0);
    }

    public static GameObject NetworkInstantiate(this GameObject gameObject, Vector2f position, float rotation, int group)
    {
        return (GameObject)Network.Instantiate(gameObject, position, Quaternion.Euler(0, 0, rotation), group);
    }

    #endregion

    #endregion

    #region Layer Stuff

    public static int GetLayer(this GameObject gameObject)
    {
        return gameObject.layer;
    }

    public static string GetLayerName(this GameObject gameObject)
    {
        return new LayerMaskF(gameObject.layer).Name;
    }

    public static void SetLayer(this GameObject gameObject, string layer)
    {
        gameObject.layer = Layer.IndexFromName(layer);
    }

    public static void SetLayer(this GameObject gameObject, int layerId)
    {
        gameObject.layer = layerId;
    }

    #endregion

    public static void SetIsRendererEnabledRecursively(this GameObject gameObject, bool enabled)
    {
        var r = gameObject.renderer;
        if (r != null)
        {
            r.enabled = enabled;
        }

        foreach (GameObject child in gameObject.GetChildren())
        {
            child.SetIsRendererEnabledRecursively(enabled);
        }
    }

    public static void SetIsRendererEnabledRecursively(this Component component, bool enabled)
    {
        var r = component.renderer;
        if (r != null)
        {
            r.enabled = enabled;
        }

        foreach (GameObject child in component.GetChildren())
        {
            child.SetIsRendererEnabledRecursively(enabled);
        }
    }
}

#endregion

#region Vector Extensions

public static class VectorExtensions
{
    public static float GetAxis(this Vector2 v, Axis axis)
    {
        return (axis == Axis.Horizontal) ? v.x : v.y;
    }


    public static float Length(this Vector2 vector)
    {
        return vector.magnitude;
    }

    public static float LengthSquared(this Vector2 vector)
    {
        return vector.sqrMagnitude;
    }

    public static Vector2 NormalizeOrZero(this Vector2 value)
    {
        // FlaiMath.NormalizeOrZero
        value.Normalize();
        if (!Check.IsValid(value))
        {
            return Vector2.zero;
        }

        return value;
    }

    public static Vector2 Divide(this Vector2 value, Vector2 divisor)
    {
        return new Vector3(value.x / divisor.x, value.y / divisor.y);
    }

    public static Vector2 Multiply(this Vector2 value, Vector2 multiplier)
    {
        return new Vector3(value.x * multiplier.x, value.y * multiplier.y);
    }

    public static Vector3 Divide(this Vector3 value, Vector3 divisor)
    {
        return new Vector3(value.x / divisor.x, value.y / divisor.y, value.z / divisor.z);
    }

    public static Vector3 Multiply(this Vector3 value, Vector3 multiplier)
    {
        return new Vector3(value.x * multiplier.x, value.y * multiplier.y, value.z * multiplier.z);
    }

    public static Vector2f ToVector2f(this Vector2 v)
    {
        return new Vector2f { X = v.x, Y = v.y };
    }

    public static Vector2f ToVector2f(this Vector3 v)
    {
        return new Vector2f { X = v.x, Y = v.y };
    }

    public static Vector3 ToVector3(this Vector2 vector)
    {
        return vector;
    }

    public static Vector2 ToVector2(this Vector3 vector)
    {
        return vector;
    }

    public static Vector2 Rotate(Vector2 point, float radians)
    {
        return Vector2f.Rotate(point.ToVector2f(), radians);
    }

    public static Vector2 Rotate(Vector2 point, float radians, Vector2 origin)
    {
        return Vector2f.Rotate(point.ToVector2f(), radians, origin);
    }
}

#endregion

#region Color Extensions

public static class ColorExtensions
{
    public static int ToInt(this Color32 color)
    {
        return ColorHelper.ColorFToInt(color);
    }

    public static ColorF ToColorF(this Color color)
    {
        return color;
    }

    public static Color32[] ToColor32(this ColorF[] array)
    {
        return ColorHelper.ConvertToColor32(array);
    }

    public static ColorF[] ToColorF(this Color32[] array)
    {
        return ColorHelper.ConvertToColorF(array);
    }

    public static bool Equals(this Color32 color, Color32 other)
    {
        return color.r == other.r && color.g == other.g && color.b == other.b && color.a == other.a;
    }

    public static bool Equals(this Color color, Color other)
    {
        return color.r == other.r && color.g == other.g && color.b == other.b && color.a == other.a;
    }

    public static Color32 MultiplyAlpha(this Color32 color, float alpha)
    {
        return new Color32(color.r, color.g, color.b, (byte)FlaiMath.Clamp(color.a * alpha, 0, 255));
    }

    public static Vector3 ToVector3(this Color color)
    {
        return color.ToColorF().ToVector3();
    }

    public static Vector4 ToVector4(this Color color)
    {
        return color.ToColorF().ToVector4();
    }

}

#endregion

#region Texture Extensions

public static class TextureExtensions
{
    public static Size GetSize(this Texture2D texture)
    {
        return new Size(texture.width, texture.height);
    }
}

#endregion

#region Sprite Extensions

public static class SpriteExtensions
{
    public static SizeF GetSize(this Sprite sprite)
    {
        return new SizeF(sprite.rect.width, sprite.rect.height);
    }
}

#endregion

#region Rect Extensions

public static class RectExtensions
{
    public static RectangleF AsInflated(this Rect rect, float amount)
    {
        return new Rect(rect.x - amount, rect.y - amount, rect.width + amount * 2, rect.height + amount * 2);
    }

    public static RectangleF ToRectangleF(this Rect rect)
    {
        return rect;
    }
}

#endregion

#region Physics Extensions

public static class PhysicsExtensions
{
    // really hacked, collider2D.bounds is coming in Unity 4.5
    public static RectangleF GetBoundsHack(this Collider2D collider)
    {
        Ensure.NotNull(collider);
        if (collider is BoxCollider2D)
        {
            float rotation = collider.transform.GetRotation2D();
            BoxCollider2D boxCollider = collider as BoxCollider2D;

            Vector2f size = collider.gameObject.GetScale2D() * boxCollider.size;
            Vector2f center = boxCollider.center.ToVector2f() / boxCollider.size;
            Vector2f origin = Vector2f.One * 0.5f - center;
            Vector2f startPosition = collider.gameObject.GetPosition2D() - origin * size;

            TransformedRectangleF transformedBounds = TransformedRectangleF.CreateRotated(new RectangleF(startPosition.X, startPosition.Y, size.X, size.Y), origin * size + startPosition, rotation);
            return transformedBounds.Bounds;
        }

        throw new NotImplementedException("");
    }

    // really hacked, collider2D.bounds is coming in Unity 4.5
    public static RectangleF GetArea(this BoxCollider2D collider, out Vector2f rotationOrigin)
    {
        Ensure.NotNull(collider);
        if (collider is BoxCollider2D)
        {
            float rotation = collider.transform.GetRotation2D();
            BoxCollider2D boxCollider = collider as BoxCollider2D;

            Vector2f size = collider.transform.lossyScale.ToVector2f() * boxCollider.size;
            Vector2f center = boxCollider.center.ToVector2f() / boxCollider.size;
            Vector2f origin = Vector2f.One * 0.5f - center;
            Vector2f startPosition = collider.gameObject.GetPosition2D() - origin * size;

            rotationOrigin = origin*size + startPosition;
            return new RectangleF(startPosition.X, startPosition.Y, size.X, size.Y);
        }

        throw new NotImplementedException("");
    }

    // really hacked, doesnt take rotation in account, collider2D.bounds is coming in Unity 4.5
    // doesn't work properly i think with rotations. trying to fix it for the GetBoundsHack
    public static Vector2 GetCenterHack(this Collider2D collider)
    {
        Ensure.NotNull(collider);
        if (collider is BoxCollider2D)
        {
            BoxCollider2D boxCollider = collider as BoxCollider2D;
            Vector2f size = collider.gameObject.GetScale2D() * boxCollider.size;
            return (Vector2f.One * 0.5f - boxCollider.center.ToVector2f()) * size;
        }

        throw new NotImplementedException("");
    }

    public static Bounds AsExpanded(this Bounds bounds, float amount)
    {
        bounds.Expand(amount);
        return bounds;
    }

    public static bool DidHit(this RaycastHit2D raycastHit)
    {
        return raycastHit.collider != null;
    }

    public static RectangleF ToRectangleF(this Bounds bounds)
    {
        return new RectangleF(bounds.min.x, bounds.min.y, bounds.extents.x * 2, bounds.extents.y * 2);
    }
}

#endregion

#region Camera Extensions

public static class CameraExtensions
{
    public static RectangleF GetArea(this Camera camera)
    {
        Ensure.True(camera.orthographic);
        float height = camera.orthographicSize * 2;
        float width = height * camera.aspect;
        return RectangleF.CreateCentered(camera.transform.position, new SizeF(width, height));
    }
}

#endregion

public static class NetworkingExtensions
{
    public static void Serialize(this BitStream stream, ref Vector2f vector)
    {
        stream.Serialize(ref vector.X);
        stream.Serialize(ref vector.Y);
    }

    // do i want separate Serialize and Deserialize methods..?
    public static void Serialize<T>(this BitStream stream, NetworkMessageInfo info, T networkState)
        where T : INetworkState<T>
    {
        networkState.Serialize(stream, info);
    }

    public static T Deserialize<T>(this BitStream stream, NetworkMessageInfo info)
       where T : INetworkState<T>, new()
    {
        T state = default(T);
        return state.Deserialize(stream, info);
    }
}